/**
 * DO NOT EDIT THIS FILE! This is an auto-generated source code. To update this file, go to the project folder, then
 * execute:
 * 
 * <pre>
 * &gt; ant generateTrackFactorySetup
 * </pre>
 * 
 */
// --------------------------------------
// GenomeBrowser Project
//
// TrackFactorySetup.java
// Since: 2007/07/18
//
// --------------------------------------
package org.utgenome.gwt.utgb.client.track;

public class TrackFactorySetup {
	public static void initialize() {
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.AnnotationTrack", org.utgenome.gwt.utgb.client.track.lib.AnnotationTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.AlignmentViewTrack",
				org.utgenome.gwt.utgb.client.track.lib.AlignmentViewTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.BrowserTrack",
				org.utgenome.gwt.utgb.client.track.lib.debug.BrowserTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.DebugToolBoxTrack",
				org.utgenome.gwt.utgb.client.track.lib.debug.DebugToolBoxTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.PropertyEditTrack",
				org.utgenome.gwt.utgb.client.track.lib.debug.PropertyEditTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.SampleGeneTableTrack",
				org.utgenome.gwt.utgb.client.track.lib.debug.SampleGeneTableTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.SampleGeneTrack",
				org.utgenome.gwt.utgb.client.track.lib.debug.SampleGeneTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.SQLiteTrack", org.utgenome.gwt.utgb.client.track.lib.debug.SQLiteTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.debug.URLQueryArgumentTrack",
				org.utgenome.gwt.utgb.client.track.lib.debug.URLQueryArgumentTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.KeywordSearchTrack",
				org.utgenome.gwt.utgb.client.track.lib.KeywordSearchTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.LegacyTrack", org.utgenome.gwt.utgb.client.track.lib.LegacyTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.NavigatorTrack", org.utgenome.gwt.utgb.client.track.lib.NavigatorTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBAddTrackTrack",
				org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBAddTrackTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBPropertyTrack",
				org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBPropertyTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBRulerTrack",
				org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBRulerTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBTrack", org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.OperationTrack", org.utgenome.gwt.utgb.client.track.lib.old.OperationTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ParameterTrack", org.utgenome.gwt.utgb.client.track.lib.ParameterTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.RevisionSelectTrack",
				org.utgenome.gwt.utgb.client.track.lib.RevisionSelectTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.MiniBrowserTrack", org.utgenome.gwt.utgb.client.track.lib.MiniBrowserTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.GenomeTrack", org.utgenome.gwt.utgb.client.track.lib.GenomeTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.DASTrack", org.utgenome.gwt.utgb.client.track.lib.DASTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.BEDTrack", org.utgenome.gwt.utgb.client.track.lib.BEDTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.BEDCanvasTrack", org.utgenome.gwt.utgb.client.track.lib.BEDCanvasTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.RulerTrack", org.utgenome.gwt.utgb.client.track.lib.RulerTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ScrollButtonTrack", org.utgenome.gwt.utgb.client.track.lib.ScrollButtonTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.SequenceRulerTrack",
				org.utgenome.gwt.utgb.client.track.lib.SequenceRulerTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.SpeciesSelectTrack",
				org.utgenome.gwt.utgb.client.track.lib.SpeciesSelectTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.TargetSelectTrack", org.utgenome.gwt.utgb.client.track.lib.TargetSelectTrack
				.factory());
		TrackFactoryHolder
				.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ToolBoxTrack", org.utgenome.gwt.utgb.client.track.lib.ToolBoxTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.TrackTreeTrack", org.utgenome.gwt.utgb.client.track.lib.TrackTreeTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ValueSelectorTrack",
				org.utgenome.gwt.utgb.client.track.lib.ValueSelectorTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ViewLoaderTrack", org.utgenome.gwt.utgb.client.track.lib.ViewLoaderTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.WindowControlTrack",
				org.utgenome.gwt.utgb.client.track.lib.WindowControlTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.GeneCanvasTrack", org.utgenome.gwt.utgb.client.track.lib.GeneCanvasTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.RibbonRulerTrack", org.utgenome.gwt.utgb.client.track.lib.RibbonRulerTrack
				.factory());

		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ChromosomeMapTrack",
				org.utgenome.gwt.utgb.client.track.lib.ChromosomeMapTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.BSSCanvasTrack", org.utgenome.gwt.utgb.client.track.lib.BSSCanvasTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.DBSelectTrack", org.utgenome.gwt.utgb.client.track.lib.DBSelectTrack
				.factory());

		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.WIGGraphCanvasTrack",
				org.utgenome.gwt.utgb.client.track.lib.WIGGraphCanvasTrack.factory());

		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.SAMTrack", org.utgenome.gwt.utgb.client.track.lib.SAMTrack.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.SAMQueryTrack", org.utgenome.gwt.utgb.client.track.lib.SAMQueryTrack
				.factory());
		TrackFactoryHolder.addTrackFactory("org.utgenome.gwt.utgb.client.track.lib.ReadTrack", org.utgenome.gwt.utgb.client.track.lib.ReadTrack.factory());

		TrackFactoryHolder.addTrackGroupFactory("org.utgenome.gwt.utgb.client.track.lib.debug.DrosophilaTrackGroup",
				org.utgenome.gwt.utgb.client.track.lib.debug.DrosophilaTrackGroup.factory());
		TrackFactoryHolder.addTrackGroupFactory("org.utgenome.gwt.utgb.client.track.lib.debug.SampleGeneTrackGroup",
				org.utgenome.gwt.utgb.client.track.lib.debug.SampleGeneTrackGroup.factory());
		TrackFactoryHolder.addTrackGroupFactory("org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBTrackGroup",
				org.utgenome.gwt.utgb.client.track.lib.old.OldUTGBTrackGroup.factory());
		TrackFactoryHolder.addTrackGroupFactory("org.utgenome.gwt.utgb.client.track.TrackGroup", org.utgenome.gwt.utgb.client.track.TrackGroup.factory());

	}
}
